### ISSUE TITLE
`OverpassState` type error

### ISSUE THREAD

**Issue by multimeric** [JuanCouste/overpass-ql-ts#17]
I think there's an issue with the `OverpassState` methods:
```typescript
const loadArea = api.createFunction([ParamType.GeoPos], (s: OverpassState, point: ParamItem<OverpassGeoPos>) => 
  s.aroundCenter(10, point)
)
```

Gives:
```
Expected 3 arguments, but got 2.ts(2554)
(method) aroundCenter(target: OverpassQueryTargetExpression, radius: OverpassExpression<number>, center: OverpassExpression<OverpassGeoPos>): OverpassTargetStateStatement
```

This is also true with `byTags` etc.

**Comment by JuanCouste** [comment]
Hi, the error is correct, when using filters without specifying a target (such as node, way, etc) you need to include it as a parameter (target: OverpassQueryTargetExpression).

You understandably did not infer this from the documentation, because following aroundCenter definition show only two arguments. The root function is actually a proxy for the latter.

This is not ideal, and its currently being deprecated.

Here is an extract of the docs included in the package, consider using a variation of theese
```typescript
(s: OverpassState) => [
	s.node.byId(1),
	s[OverpassQueryTarget.NodeWayRelation].byId(1),
	s.byId("way", 1),
	s.byId(OverpassQueryTarget.Relation, 1)
]
```

You can specify aditional constraints for a filter query by using .and(...)
```typescript
...
s.node.aroundCenter(10, point).and(c => c.byTags({ name: "Some name" }))
...
```

**Comment by JuanCouste** [comment]
Sorry for the late response @multimeric , I'am not getting notifications for issues ...
